# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Kendall's Tau-A
#'
#' @param x A vector of values
#' @param y A vector of values (each y-value forms a pair with the corresponding x-value)
#' @export
fasttau <- function(x, y) {
    .Call('_fasttau_fasttau', PACKAGE = 'fasttau', x, y)
}

